name: Auto deploy enzo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy the Docker image
      run: docker-compose up --build --force-recreate --no-deps --detach && docker image prune -f
